"""Seal a short secret so it can wait in a database row without being readable there.

Used for the outbox: a student's generated password has to survive until the e-mail
job runs, and the e-mail job may run on another replica, so it cannot live in memory.
Fernet (AES-128-CBC + HMAC-SHA256, from `cryptography`) keyed from SECRET_KEY: anyone
with only the database sees an opaque token; the app opens it in memory, sends, and
overwrites the row with a placeholder.

Rotating SECRET_KEY makes tokens sealed under the old key unreadable, which for an
outbox row means the job fails and is retried until it exhausts its budget. That is
the right failure: a credential that cannot be delivered is regenerated by the
teacher, not recovered from a log.
"""

from __future__ import annotations

import base64
import hashlib

from cryptography.fernet import Fernet, InvalidToken

from submissions_checker.core.config import get_settings

_PREFIX = "sealed:"


def _secret_key() -> str:
    return get_settings().secret_key


def _fernet() -> Fernet:
    digest = hashlib.sha256(b"submissions-checker/sealed/v1:" + _secret_key().encode()).digest()
    return Fernet(base64.urlsafe_b64encode(digest))


def seal(value: str) -> str:
    return _PREFIX + _fernet().encrypt(value.encode()).decode()


def is_sealed(value: object) -> bool:
    return isinstance(value, str) and value.startswith(_PREFIX)


def unseal(token: str) -> str:
    if not is_sealed(token):
        raise ValueError("not a sealed value")
    try:
        return _fernet().decrypt(token[len(_PREFIX) :].encode()).decode()
    except InvalidToken as exc:
        raise ValueError("sealed value cannot be opened with this SECRET_KEY") from exc
